const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const PDFDocument = require('pdfkit');

const envPath = path.join(__dirname, '../.env.local');
if (!fs.existsSync(envPath)) {
  console.error('Missing .env.local');
  process.exit(1);
}

const envContent = fs.readFileSync(envPath, 'utf8');
const envVars = {};
envContent.split('\n').forEach((line) => {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) return;
  const parts = trimmed.split('=');
  if (parts.length >= 2) {
    envVars[parts[0].trim()] = parts.slice(1).join('=').trim();
  }
});

const uri = envVars['MONGODB_URI'];
if (!uri) {
  console.error('Missing MONGODB_URI in .env.local');
  process.exit(1);
}

const UserSchema = new mongoose.Schema({
  username: String,
  profileDetails: {
    fullName: String,
    dob: Date,
    email: String,
    mobile: String,
    address: String,
    isSubmitted: Boolean,
  }
});

const User = mongoose.models.User || mongoose.model('User', UserSchema);

async function testPdfGen() {
  console.log('Connecting to database...');
  await mongoose.connect(uri);
  console.log('Connected!');

  const user = await User.findOne({ username: 'darshitdudhaiya' });
  if (!user) {
    console.error('User darshitdudhaiya not found in database.');
    await mongoose.disconnect();
    process.exit(1);
  }

  console.log('User details found:', user.profileDetails);

  const details = user.profileDetails;
  const formattedDob = details.dob
    ? new Date(details.dob).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })
    : 'N/A';

  console.log('Generating PDF buffer...');
  try {
    const pdfBuffer = await new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
      });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      doc.rect(0, 0, 595.28, 120).fill('#1e1b4b');

      doc.font('Helvetica-Bold')
         .fillColor('#ffffff')
         .fontSize(24)
         .text('USER PROFILE SPECIFICATION', 50, 45, { characterSpacing: 1 });
      
      doc.font('Helvetica')
         .fontSize(10)
         .fillColor('#a5b4fc')
         .text(`Generated on ${new Date().toLocaleDateString('en-US')}`, 50, 78);

      doc.fillColor('#111827');
      
      doc.font('Helvetica-Bold')
         .fontSize(16)
         .fillColor('#1e1b4b')
         .text('Personal Details', 50, 150, { underline: true });
      
      doc.moveTo(50, 172)
         .lineTo(545, 172)
         .strokeColor('#e5e7eb')
         .lineWidth(1)
         .stroke();

      let currentY = 190;
      const drawRow = (label, value) => {
        doc.font('Helvetica-Bold')
           .fontSize(11)
           .fillColor('#6b7280')
           .text(label, 50, currentY, { width: 150 });
        
        doc.font('Helvetica')
           .fontSize(11)
           .fillColor('#111827')
           .text(value, 200, currentY, { width: 345 });
        
        currentY += doc.heightOfString(value, { width: 345 }) + 15;
        doc.moveTo(50, currentY - 5)
           .lineTo(545, currentY - 5)
           .strokeColor('#f3f4f6')
           .stroke();
      };

      drawRow('Full Name', details.fullName || 'N/A');
      drawRow('Date of Birth', formattedDob);
      drawRow('Email Address', details.email || 'N/A');
      drawRow('Mobile Number', details.mobile || 'N/A');
      drawRow('Residential Address', details.address || 'N/A');

      currentY += 20;
      doc.rect(50, currentY, 495, 60)
         .fillColor('#f9fafb')
         .rect(50, currentY, 495, 60)
         .strokeColor('#e5e7eb')
         .fillAndStroke();

      doc.font('Helvetica-Bold')
         .fillColor('#374151')
         .fontSize(9)
         .text('Declaration & Integrity Statement:', 65, currentY + 12);

      doc.font('Helvetica')
         .fillColor('#6b7280')
         .fontSize(9)
         .text('The information provided above represents the accurate and official personal profile details stored securely in the system registry.', 65, currentY + 28, { width: 460 });

      doc.font('Helvetica')
         .fontSize(8)
         .fillColor('#9ca3af')
         .text('This document was automatically generated by the web application service.', 50, 750, { align: 'center' });

      doc.end();
    });

    const outputPath = path.join(__dirname, '../test_profile.pdf');
    fs.writeFileSync(outputPath, pdfBuffer);
    console.log('PDF generated successfully at:', outputPath);
  } catch (error) {
    console.error('PDF Generation Exception:', error);
  }

  await mongoose.disconnect();
}

testPdfGen();
